spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5433/weather
    name: postgres
    password: postgres
  liquibase:
    enabled: true
    change-log: db/changelog/changelog-master.yml
cloud:
  openfeign:
    client:
      config:
        default:
          connectTimeout: 5000
          readTimeout: 5000
          loggerLevel: basic

server:
  port: 8090

# Swagger Configuration
springdoc:
  api-docs:
    enabled: true
    path: /rest-api-docs
  swagger-ui:
    path: /swagger-ui
app:
  weather-api:
    key: ${WEATHER_API_KEY:ea7aef8e9e254bd4a58170343232402}
    city-name: ${WEATHER_API_CITY_NAME:Moscow}
    forecast-days-count: ${WEATHER_API_FORECAST_DAYS_COUNT:2}
